In [ ]:
1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size 
of the memory occupied by the array.

In [1]:
import numpy as np
arr1 = np.array([1,7,13,105])
print("Array:",arr1)
memory = arr1.nbytes
print("Size of memory:",memory)

Array: [  1   7  13 105]
Size of memory: 16


In [ ]:
2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and
   less_equal) of two given arrays.

In [3]:
arr1 = np.array([1,7,8,6,9])
arr2 = np.array([5,6,78,96,21])

for i in arr1:
    for j in arr2:
        if i>j:
            print(f"{i} is greater than {j}.")
        
        elif i>=j:
            print(f"{i} is greater_equal to {j}.")
        
        elif i<j:
            print(f"{i} is less than {j}.")
            
        elif i<=j:
            print(f"{i} is less_equal to {j}.")

1 is less than 5.
1 is less than 6.
1 is less than 78.
1 is less than 96.
1 is less than 21.
7 is greater than 5.
7 is greater than 6.
7 is less than 78.
7 is less than 96.
7 is less than 21.
8 is greater than 5.
8 is greater than 6.
8 is less than 78.
8 is less than 96.
8 is less than 21.
6 is greater than 5.
6 is greater_equal to 6.
6 is less than 78.
6 is less than 96.
6 is less than 21.
9 is greater than 5.
9 is greater than 6.
9 is less than 78.
9 is less than 96.
9 is less than 21.


In [ ]:
3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 
10 twentys and 10 fiftys.

In [17]:
arr_0 = np.zeros(10)
print(arr_0)
print()

arr_1 = np.ones(10)
print(arr_1)
print()

arr_5 = np.ones(10)*5
print(arr_5)
print()

arr_10 = np.ones(10)*10
print(arr_10)
print()

arr_20 = np.ones(10)*20
print(arr_20)
print()

arr_50 = np.ones(10)*50
print(arr_50)
print()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]



In [ ]:
4. Write a NumPy program to create an array of integers from 30 to 70.

In [31]:
arr = np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
5. Write a NumPy program to create an array of integers from 50 to 95.

In [32]:
arr = np.arange(50,95)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [ ]:
6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [33]:
arr = np.arange(20,81,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [ ]:
7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [34]:
arr = np.arange(21,82,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79 81]


In [ ]:
8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

In [35]:
arr = np.random.randint(10,40,15)
print(arr)

[38 27 31 15 30 30 21 32 14 33 23 12 39 32 21]


In [ ]:
9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [36]:
arr = np.random.randint(30,50,10)
print(arr)

[33 37 47 38 48 47 44 40 33 46]


In [ ]:
10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [37]:
arr = np.random.randint(50,90,20)
print(arr)

[85 88 56 52 70 55 79 84 77 86 54 64 52 84 57 61 78 80 84 78]


In [ ]:
11. Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.

In [40]:
arr_1 = np.random.randint(1,10,5)
print("Array_1:",arr_1)
print()
arr_2 = np.random.randint(11,20,5)
print("Array_2",arr_2)
print()

print("Addition of Array_1 and Array_2:",arr_1+arr_2)
print()
print("Subctraction of Array_1 and Array_2:",arr_1-arr_2)
print()
print("Multiplication of Array_1 and Array_2:",arr_1+arr_2)
print()
print("Division of Array_1 and Array_2:",arr_1+arr_2)


Array_1: [9 9 7 8 5]

Array_2 [17 14 18 13 14]

Addition of Array_1 and Array_2: [26 23 25 21 19]

Subctraction of Array_1 and Array_2: [ -8  -5 -11  -5  -9]

Multiplication of Array_1 and Array_2: [26 23 25 21 19]

Division of Array_1 and Array_2: [26 23 25 21 19]


In [ ]:
12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [41]:
arr = np.random.randint(10,21,size=(3,4))
arr

array([[11, 13, 11, 10],
       [12, 15, 15, 12],
       [13, 15, 15, 11]])

In [ ]:
13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1,
the rest are 0.

In [69]:
arr = np.diag([1,1,1])
arr    

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
14. Write a NumPy program to find the number of rows and columns in a given matrix. 

In [47]:
arr = np.random.randint(1,25,size=(5,5))
print("Array:",arr)
print()

print("Rows:",arr.shape[0])

print("Columns:",arr.shape[1])

Array: [[14  5 17  2 16]
 [18 12 21 23 20]
 [11 15 12 17 15]
 [ 7  1  3  6 24]
 [10 17 22  4 21]]

Rows: 5
Columns: 5


In [ ]:
15. Write a NumPy program to create a 5x5 zero matrix with elements on the 
main diagonal equal to 1, 2, 3, 4, 5.

In [68]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [49]:
arr = np.random.randint(0,10,size=(3,3,3))
arr

array([[[4, 4, 4],
        [5, 8, 2],
        [6, 2, 7]],

       [[7, 9, 5],
        [2, 0, 8],
        [1, 5, 4]],

       [[5, 9, 3],
        [9, 9, 9],
        [5, 4, 5]]])

In [ ]:
17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

In [50]:
arr = np.random.randint(0,15,size=(2,3,4))
arr

array([[[ 8,  2,  1,  5],
        [ 8,  8,  5, 10],
        [ 1,  5,  7, 10]],

       [[ 1,  0,  2, 10],
        [ 9,  3,  7,  0],
        [ 4, 13,  8,  5]]])

In [ ]:
18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [51]:
lst = [1,2,3,4,5]

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [ ]:
19. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [52]:
arr = np.random.randint(2,10,size=(3,3))
arr

array([[9, 5, 5],
       [2, 5, 3],
       [5, 4, 4]])

In [ ]:
20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [53]:
arr = np.arange(12,38)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [ ]:
21. Write a NumPy program to reverse an array (the first element becomes the last).

In [55]:
arr = np.arange(1,6)
print("Array:",arr)
print()
print("After Reverse:")
arr[::-1]

Array: [1 2 3 4 5]

After Reverse:


array([5, 4, 3, 2, 1])

In [ ]:
22. Write a NumPy program to convert an data type into to a floating type.

In [62]:
arr_1 = np.array([1,2,3,4,5])
print("Array:",arr)
print("data type:",arr_1.dtype)
print()
arr_2 = arr_1.astype(float)
print("After Array:",arr_2)
print("After data type:",arr_2.dtype)

Array: [1 2 3 4 5]
data type: int32

After Array: [1. 2. 3. 4. 5.]
After data type: float64


In [ ]:
23. Write a NumPy program to convert a list array.

In [63]:
lst = [1,2,3,4,5]
print(type(lst))

arr = np.array(lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
24. Write a NumPy program to get the element-wise remainder of an array of division.

In [66]:
arr_1 = np.array([50,87,96,31,68])

arr_2 = np.array([1,2,3,4,5])

print(arr_1%arr_2)

[0 1 0 3 3]


In [ ]:
25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 
which are divisible by 3.

In [64]:
arr = np.arange(20,50)

lst = []
for i in arr:
    num = i%3
    lst.append(num)
    
print("Reminder",lst)

Reminder [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1]
