In [306]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder 
from sklearn.model_selection import train_test_split

# Dataset-1

In [15]:
df = pd.read_csv('ToyotaCorolla.csv',encoding='ISO-8859-1')
df.head()

Id                                           Model  Price  Age_08_04  \
0   1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1   2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2   3   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3   4   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4   5     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   

   Mfg_Month  Mfg_Year     KM Fuel_Type  HP  Met_Color  ... Central_Lock  \
0         10      2002  46986    Diesel  90          1  ...            1   
1         10      2002  72937    Diesel  90          1  ...            1   
2          9      2002  41711    Diesel  90          1  ...            0   
3          7      2002  48000    Diesel  90          0  ...            0   
4          3      2002  38500    Diesel  90          0  ...            1   

   Powered_Windows  Power_Steering  Radio  Mistlamps  Sport_Model  \
0                1               1      0          0            0   
1                0               1      0          0            0   
2                0               1      0          0            0   
3                0               1      0          0            0   
4                1               1      0          1            0   

   Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar  
0                 1             0               0        0  
1                 1             0               0        0  
2                 1             0               0        0  
3                 1             0               0        0  
4                 1             0               0        0  

[5 rows x 38 columns]

In [16]:
df.shape

(1436, 38)

In [30]:
df["Model"].nunique()

372

In [19]:
df = df.drop('Id',axis=1)

In [27]:
model = df[["Model"]]


pandas.core.frame.DataFrame

In [29]:
model_oe = OrdinalEncoder()
model_oe = model_oe.fit(model)
model_num = model_oe.transform(model)
model_num

array([[257.],
       [257.],
       [365.],
       ...,
       [  8.],
       [  8.],
       [163.]])

In [32]:
df["Model Num"] = model_num

In [34]:
df["Model Num"].nunique()

372

In [36]:
df.columns

Index(['Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'cc', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Tow_Bar', 'Model Num'],
      dtype='object')

In [37]:
#fuel-type
df["Fuel_Type"].nunique()

3

In [39]:
df["Fuel_Type"].value_counts().to_dict()

{'Petrol': 1264, 'Diesel': 155, 'CNG': 17}

In [42]:
df["Fuel_Type"] = df["Fuel_Type"].replace({'Petrol': 0, 'Diesel': 1, 'CNG': 1})

In [44]:
df['Color'].nunique()

10

In [45]:
color_num = OrdinalEncoder()
color_num = color_num.fit(df[["Color"]])
color_num = color_num.transform(df[["Color"]])
color_num

array([[2.],
       [6.],
       [2.],
       ...,
       [2.],
       [4.],
       [3.]])

In [47]:
df["Color Num"] = color_num

In [54]:
df.drop('Model',axis=1,inplace=True)
df

Price  Age_08_04  Mfg_Month  Mfg_Year     KM  Fuel_Type   HP  Met_Color  \
0     13500         23         10      2002  46986          1   90          1   
1     13750         23         10      2002  72937          1   90          1   
2     13950         24          9      2002  41711          1   90          1   
3     14950         26          7      2002  48000          1   90          0   
4     13750         30          3      2002  38500          1   90          0   
...     ...        ...        ...       ...    ...        ...  ...        ...   
1431   7500         69         12      1998  20544          0   86          1   
1432  10845         72          9      1998  19000          0   86          0   
1433   8500         71         10      1998  17016          0   86          0   
1434   7250         70         11      1998  16916          0   86          1   
1435   6950         76          5      1998      1          0  110          0   

       Color  Automatic    cc  Doors  Cylinders  Gears  Quarterly_Tax  Weight  \
0       Blue          0  2000      3          4      5            210    1165   
1     Silver          0  2000      3          4      5            210    1165   
2       Blue          0  2000      3          4      5            210    1165   
3      Black          0  2000      3          4      5            210    1165   
4      Black          0  2000      3          4      5            210    1170   
...      ...        ...   ...    ...        ...    ...            ...     ...   
1431    Blue          0  1300      3          4      5             69    1025   
1432    Grey          0  1300      3          4      5             69    1015   
1433    Blue          0  1300      3          4      5             69    1015   
1434    Grey          0  1300      3          4      5             69    1015   
1435   Green          0  1600      5          4      5             19    1114   

      Mfr_Guarantee  BOVAG_Guarantee  Guarantee_Period  ABS  Airbag_1  \
0                 0                1                 3    1         1   
1                 0                1                 3    1         1   
2                 1                1                 3    1         1   
3                 1                1                 3    1         1   
4                 1                1                 3    1         1   
...             ...              ...               ...  ...       ...   
1431              1                1                 3    1         1   
1432              0                1                 3    1         1   
1433              0                1                 3    0         1   
1434              1                1                 3    0         0   
1435              0                0                 3    0         1   

      Airbag_2  Airco  Automatic_airco  Boardcomputer  CD_Player  \
0            1      0                0              1          0   
1            1      1                0              1          1   
2            1      0                0              1          0   
3            1      0                0              1          0   
4            1      1                0              1          0   
...        ...    ...              ...            ...        ...   
1431         1      1                0              0          0   
1432         1      0                0              0          0   
1433         1      0                0              0          0   
1434         0      0                0              0          0   
1435         0      0                0              0          0   

      Central_Lock  Powered_Windows  Power_Steering  Radio  Mistlamps  \
0                1                1               1      0          0   
1                1                0               1      0          0   
2                0                0               1      0          0   
3                0                0               1      0          0   
4

In [55]:
df.drop('Color',axis=1,inplace=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Price             1436 non-null   int64  
 1   Age_08_04         1436 non-null   int64  
 2   Mfg_Month         1436 non-null   int64  
 3   Mfg_Year          1436 non-null   int64  
 4   KM                1436 non-null   int64  
 5   Fuel_Type         1436 non-null   int64  
 6   HP                1436 non-null   int64  
 7   Met_Color         1436 non-null   int64  
 8   Automatic         1436 non-null   int64  
 9   cc                1436 non-null   int64  
 10  Doors             1436 non-null   int64  
 11  Cylinders         1436 non-null   int64  
 12  Gears             1436 non-null   int64  
 13  Quarterly_Tax     1436 non-null   int64  
 14  Weight            1436 non-null   int64  
 15  Mfr_Guarantee     1436 non-null   int64  
 16  BOVAG_Guarantee   1436 non-null   int64  


In [58]:
x = df.drop('Price',axis=1)
y = df["Price"]

In [62]:
len(x)

1436

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45)

In [60]:
len(x_train)

1148

In [61]:
len(x_test)

288

In [65]:
df.corr()

Price  Age_08_04  Mfg_Month  Mfg_Year        KM  \
Price             1.000000  -0.876590  -0.018138  0.885159 -0.569960   
Age_08_04        -0.876590   1.000000  -0.123255 -0.983661  0.505672   
Mfg_Month        -0.018138  -0.123255   1.000000 -0.057416 -0.020630   
Mfg_Year          0.885159  -0.983661  -0.057416  1.000000 -0.504974   
KM               -0.569960   0.505672  -0.020630 -0.504974  1.000000   
Fuel_Type         0.038516  -0.092611   0.049646  0.084162  0.433160   
HP                0.314990  -0.156622  -0.039312  0.164697 -0.333538   
Met_Color         0.108905  -0.108150   0.030266  0.103310 -0.080503   
Automatic         0.033081   0.031717   0.009146 -0.033567 -0.081854   
cc                0.126389  -0.098084   0.037387  0.091892  0.102683   
Doors             0.185326  -0.148359  -0.012069  0.151442 -0.036197   
Cylinders              NaN        NaN        NaN       NaN       NaN   
Gears             0.063104  -0.005364  -0.013063  0.007766  0.015023   
Quarterly_Tax     0.219197  -0.198431   0.031373  0.193934  0.278165   
Weight            0.581198  -0.470253  -0.002167  0.473478 -0.028598   
Mfr_Guarantee     0.197802  -0.164658  -0.005771  0.166697 -0.212851   
BOVAG_Guarantee   0.028133   0.006865  -0.003863 -0.006206  0.001438   
Guarantee_Period  0.146627  -0.152563   0.029010  0.148218 -0.138942   
ABS               0.306138  -0.412887   0.072532  0.402215 -0.177203   
Airbag_1          0.093588  -0.105406   0.003756  0.105359 -0.018012   
Airbag_2          0.248974  -0.329017   0.076749  0.317075 -0.139275   
Airco             0.429259  -0.403600   0.057088  0.395674 -0.133057   
Automatic_airco   0.588262  -0.426259  -0.049017  0.437718 -0.258221   
Boardcomputer     0.601292  -0.719449   0.017715  0.720567 -0.353862   
CD_Player         0.481374  -0.510895  -0.016736  0.517008 -0.266826   
Central_Lock      0.343458  -0.279631   0.010055  0.279490 -0.125177   
Powered_Windows   0.356518  -0.283856   0.025185  0.280996 -0.156242   
Power_Steering    0.064275  -0.069192  -0.055495  0.079676  0.007397   
Radio            -0.041887   0.013791   0.031601 -0.019607  0.013661   
Mistlamps         0.222083  -0.126895  -0.033504  0.133737 -0.074327   
Sport_Model       0.164121  -0.110988   0.052789  0.102080 -0.044784   
Backseat_Divider  0.102569  -0.116751   0.023245  0.113237 -0.045658   
Metallic_Rim      0.108564  -0.040045   0.023506  0.036022 -0.013599   
Radio_cassette   -0.043179   0.012857   0.032576 -0.018844  0.015770   
Tow_Bar          -0.172369   0.188720  -0.042170 -0.182206  0.084153   
Model Num         0.304868  -0.322985   0.007415  0.323585  0.050127   
Color Num        -0.051590   0.029712  -0.035049 -0.023532  0.038198   

                  Fuel_Type        HP  Met_Color  Automatic        cc  \
Price              0.038516  0.314990   0.108905   0.033081  0.126389   
Age_08_04         -0.092611 -0.156622  -0.108150   0.031717 -0.098084   
Mfg_Month          0.049646 -0.039312   0.030266   0.009146  0.037387   
Mfg_Year           0.084162  0.164697   0.103310  -0.033567  0.091892   
KM                 0.433160 -0.333538  -0.080503  -0.081854  0.102683   
Fuel_Type          1.000000 -0.489110  -0.004872  -0.080249  0.315170   
HP                -0.489110  1.000000   0.058712   0.013144  0.035856   
Met_Color         -0.004872  0.058712   1.000000  -0.019335  0.031812   
Automatic         -0.080249  0.013144  -0.019335   1.000000  0.066740   
cc                 0.315170  0.035856   0.031812   0.066740  1.000000   
Doors              0.027589  0.092424   0.085243  -0.027654  0.079903   
Cylinders               NaN       NaN        NaN        NaN       NaN   
Gears             -0.063182  0.209477   0.018601  -0.098555  0.014629   
Quarterly_Tax      0.835452 -0.298432   0.011326  -0.055371  0.306996   
Weight             0.560470  0.089614   0.057929   0.057249  0.335637   
Mfr_Guarantee     -0.150160  0.140026   0.154850   0.026194 -0.057407   
BOVAG_Guarantee   -0.056332  0.022701   0.0

In [66]:
df.isna().sum()

Price               0
Age_08_04           0
Mfg_Month           0
Mfg_Year            0
KM                  0
Fuel_Type           0
HP                  0
Met_Color           0
Automatic           0
cc                  0
Doors               0
Cylinders           0
Gears               0
Quarterly_Tax       0
Weight              0
Mfr_Guarantee       0
BOVAG_Guarantee     0
Guarantee_Period    0
ABS                 0
Airbag_1            0
Airbag_2            0
Airco               0
Automatic_airco     0
Boardcomputer       0
CD_Player           0
Central_Lock        0
Powered_Windows     0
Power_Steering      0
Radio               0
Mistlamps           0
Sport_Model         0
Backseat_Divider    0
Metallic_Rim        0
Radio_cassette      0
Tow_Bar             0
Model Num           0
Color Num           0
dtype: int64

In [67]:
df["Cylinders"]

0       4
1       4
2       4
3       4
4       4
       ..
1431    4
1432    4
1433    4
1434    4
1435    4
Name: Cylinders, Length: 1436, dtype: int64

In [68]:
df = pd.read_csv('food_coded.csv')
df

GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4       2          1               430           NaN           315.0   
1    3.654       1          1               610           3.0           420.0   
2      3.3       1          1               720           4.0           420.0   
3      3.2       1          1               430           3.0           420.0   
4      3.5       1          1               720           2.0           420.0   
..     ...     ...        ...               ...           ...             ...   
120    3.5       1          1               610           4.0           420.0   
121      3       1          1               265           2.0           315.0   
122  3.882       1          1               720           NaN           420.0   
123      3       2          1               720           4.0           420.0   
124    3.9       1          1               430           NaN           315.0   

     coffee                             comfort_food  \
0         1                                     none   
1         2              chocolate, chips, ice cream   
2         2          frozen yogurt, pizza, fast food   
3         2         Pizza, Mac and cheese, ice cream   
4         2             Ice cream, chocolate, chips    
..      ...                                      ...   
120       2  wine. mac and cheese, pizza, ice cream    
121       2               Pizza / Wings / Cheesecake   
122       1               rice, potato, seaweed soup   
123       1             Mac n Cheese, Lasagna, Pizza   
124       2             Chocolates, pizza, and Ritz.   

                              comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

     comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  cuisine  \
0                           9.0   2.0                             9      NaN   
1                           1.0   3.0                             1      1.0   
2                           1.0   1.0                             1      3.0   
3                           2.0   2.0                             2      2.0   
4                           1.0   1.0                             1      2.0   
..                          ...   ...                           ...      ...   
120                         NaN   3.0                             2      1.0   
121                         NaN   3.0                             3      NaN   
122                         NaN   3.0                             3      NaN   
123                         NaN   3.0                             7      1.0   
124                         NaN   NaN                             5      3.0   

                                          diet_current  diet_current_coded  \
0                                eat good and exercise                   1   
1    I eat about three times a day with some snacks...                   2   
2    toast and fruit for breakfast, salad for lunch...                   3   
3    College diet, cheap and easy foods most nights...                   2   
4    I try to eat healthy but often struggle becaus...                   2   
..                                                 ...                 ...   
120  My diet consists mainly of coffee, water, frui...                   2   
121  A college student with an imbalanced diet tryi...                   2   
122                             Rice, oatmeal, an

In [71]:
df['GPA'].isna().sum()

2

In [85]:
df["GPA"].replace({'Personal': np.nan},inplace=True)

In [86]:
df['GPA'].value_counts()

3.5          13
3            11
3.7          10
3.2          10
3.3           9
3.4           9
3.6           7
3.9           7
3.8           6
2.8           5
4             4
3.1           3
2.9           2
2.6           2
3.83          2
3.79          1
2.71          1
3.73          1
2.4           1
3.92          1
3.68          1
3.75          1
3.77          1
3.63          1
3.67          1
3.65          1
Personal      1
3.35          1
3.292         1
3.605         1
3.89          1
3.654         1
3.87          1
2.2           1
3.904         1
2.25          1
3.882         1
Name: GPA, dtype: int64

In [92]:
df.GPA.iloc[61] = np.nan

C:\Users\ABHI\AppData\Local\Temp\ipykernel_5236\4034860673.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.GPA.iloc[61] = np.nan


In [93]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35', '2.6',
       '3.67', '3.73', 3.79, '2.71', '3.68', '3.75', '3.92', '3.77',
       '3.63', '3.882'], dtype=object)

In [100]:
df['GPA'] = df['GPA'].astype(float)

In [104]:
x = df["GPA"].mean()
x

3.4186528925619832

In [105]:
df['GPA'].fillna(x,inplace=True)

In [108]:
df["calories_day"].unique()

array([nan,  3.,  4.,  2.])

In [109]:
df["calories_day"].mean()

3.0283018867924527

In [110]:
x = df["calories_day"].mode()

0    3.0
Name: calories_day, dtype: float64

In [111]:
df["calories_day"].median()

3.0

In [112]:
df["calories_day"].fillna(x,inplace=True)

In [115]:
df["comfort_food"].nunique()

124

In [118]:
df["comfort_food"].fillna(method="ffill",inplace=True)

In [119]:
df["comfort_food"].mode()

0    Chips, ice cream
Name: comfort_food, dtype: object

In [120]:
df["comfort_food"].isna().sum()

0

In [122]:
df["comfort_food_reasons"].isna().sum()

1

In [124]:
df["comfort_food_reasons"].nunique()

107

In [125]:
x = df["comfort_food_reasons"].mode()

0    boredom
Name: comfort_food_reasons, dtype: object

In [126]:
df["comfort_food_reasons"].fillna(x,inplace=True)

In [127]:
df["comfort_food_reasons"].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

In [129]:
df["calories_scone"].isna().sum()

1

In [141]:
x = df["calories_scone"].median()

In [140]:
df["calories_scone"].mode()

0    420.0
Name: calories_scone, dtype: float64

In [130]:
df["calories_scone"].mean()

505.241935483871

In [142]:
df["calories_scone"].fillna(x,inplace=True)

In [143]:
df["calories_scone"].isna().sum()

0

In [145]:
df["comfort_food"].dtype

dtype('O')

In [ ]:
df[""]

In [148]:
from sklearn.preprocessing import LabelEncoder
comfort_food = LabelEncoder()
df["comfort_food"] = comfort_food.fit_transform(df["comfort_food"])

In [153]:
df["comfort_food_reasons"].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

In [155]:
df["comfort_food_reasons"].isna().sum()

0

In [154]:
df["comfort_food_reasons"].value_counts()

boredom                              7
sadness                              3
Boredom                              3
Boredom                              3
boredom, sadness                     2
                                    ..
Usually if I'm sad or depressed.     1
No reasons                           1
boredom, stress                      1
Stress                               1
hormones, Premenstrual syndrome.     1
Name: comfort_food_reasons, Length: 108, dtype: int64

In [158]:
df["comfort_food_reasons"] = df["comfort_food_reasons"].astype(str)

In [159]:
from sklearn.preprocessing import LabelEncoder
comfort_food_reasons = LabelEncoder()
df["comfort_food_reasons"] = comfort_food_reasons.fit_transform(df[["comfort_food_reasons"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [161]:
df["comfort_food_reasons_coded"].unique()

array([ 9.,  1.,  2.,  4.,  3.,  7.,  6.,  5.,  8., nan])

In [162]:
df["comfort_food_reasons_coded"].mean()

2.69811320754717

In [163]:
df["comfort_food_reasons_coded"].median()

2.0

In [164]:
x = df["comfort_food_reasons_coded"].mode()

0    2.0
Name: comfort_food_reasons_coded, dtype: float64

In [166]:
df["comfort_food_reasons_coded"].fillna(x,inplace=True)

In [168]:
df["cuisine"].unique()

array([nan,  1.,  3.,  2.,  6.,  4.,  5.])

In [170]:
def mmm(col):
    mode = df[f'{col}'].mode()
    print(mode)
    median = df[f'{col}'].median()
    print(median)
    mean = df[f'{col}'].mean()
    print(mean)    

In [171]:
mmm('cuisine')

0    1.0
Name: cuisine, dtype: float64
1.0
1.3888888888888888


In [172]:
df["cuisine"].fillna(df["cuisine"].median(),inplace=True)

In [174]:
df["diet_current"].isna().sum()

1

In [175]:
df["diet_current"].nunique()

124

In [176]:
df["diet_current"].fillna(method='ffill',inplace=True)

In [180]:
from sklearn.preprocessing import OrdinalEncoder
diet_current = OrdinalEncoder()
df["diet_current"] = diet_current.fit_transform(df[["diet_current"]])

In [182]:
df["drink"].isna().sum()

2

In [183]:
df["drink"].unique()

array([ 1.,  2., nan])

In [186]:
df["drink"].fillna(df["drink"].mode(),inplace=True)

In [190]:
df["eating_changes"].fillna(method='ffill',inplace=True)

In [191]:
df['eating_changes'].nunique()

121

In [188]:
df["eating_changes"].unique()

array(['eat faster ', 'I eat out more than usual. ',
       'sometimes choosing to eat fast food instead of cooking simply for convenience',
       'Accepting cheap and premade/store bought foods',
       'I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ',
       'Eating rice everyday. Eating less homemade food.',
       "I started eating a lot less and healthier because I wasn't playing sports year round anymore.",
       'Freshmen year i ate very unhealthy, but now it is much healthier because of self control.',
       'I snack less',
       "I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ",
       'Nun ', 'Less meat. ',
       'I have been eating a lot more salads and soups.',
       'not as healthy because healthy food goes bad quickly and it is expensiv

In [192]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["eating_changes"] = le.fit_transform(df[["eating_changes"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [194]:
df["cook"].unique()

array([ 2.,  3.,  1.,  5.,  4., nan])

In [195]:
mmm('cook')

0    3.0
Name: cook, dtype: float64
3.0
2.7868852459016393


In [196]:
df["cook"].fillna(df["cook"].mean(),inplace=True)

In [198]:
df["drink"].unique()

array([ 1.,  2., nan])

In [200]:
mmm('drink')

0    2.0
Name: drink, dtype: float64
2.0
1.5609756097560976


In [203]:
df["drink"].fillna(df["drink"].mean(),inplace=True)

In [205]:
df["employment"].unique()

array([ 3.,  2.,  1., nan])

In [206]:
mmm('employment')

0    2.0
Name: employment, dtype: float64
2.0
2.4482758620689653


In [213]:
df["employment"]= df["employment"].fillna(df["employment"].mean())

In [215]:
df["exercise"].unique()

array([ 1.,  2.,  3., nan])

In [216]:
mmm("exercise")

0    1.0
Name: exercise, dtype: float64
1.0
1.5892857142857142


In [217]:
df["exercise"].fillna(df["exercise"].median(),inplace=True)

In [219]:
df["father_education"].unique()

array([ 5.,  2.,  4.,  1.,  3., nan])

In [223]:
mmm("father_education")

0    4.0
Name: father_education, dtype: float64
4.0
3.4838709677419355


In [222]:
df["father_education"].isna().sum()

1

In [226]:
df["father_education"].fillna(df["father_education"].median(),inplace=True)

In [228]:
df["father_profession"].unique()

array(['profesor ', 'Self employed ', 'owns business', 'Mechanic ', 'IT',
       'Taxi Driver', 'Assembler ', 'Business guy',
       'High School Principal', 'commissioner of erie county ', 'Idk',
       'Home Marker ', 'Shirt designer ', 'business owner',
       'Commidity trader ', 'Hockey Coach', 'Construction ',
       'self employed construction ', 'Engineer', 'architect', 'CFO',
       'European logistics director ', 'accountant ',
       'Commercial Real Estate', 'Manager at Pepsi', 'VP of ',
       'Beverage and Food Sales', 'Dentist ', 'Electrical Engineer',
       'Radio Telecommunications Manager', nan, 'deceased', 'Lawyer',
       'landscaping ', 'Vice President of a company',
       'Owns his own promotional company ', 'Optometrist ',
       'Biohemical Waste Elimination', 'Corporate Manager ',
       'Small business owner ', 'Welder', 'Design Engineer', 'Unknown ',
       'Banker', 'subcontractor ', 'small business owner ',
       'House Appraiser', 'not sure', 'Fireman',

In [229]:
df["father_profession"].nunique()

114

In [230]:
df["father_profession"].mode()

0         Business Owner
1          Construction 
2               Dentist 
3    Electrical Engineer
4                     IT
5                 Lawyer
6                Teacher
7         business owner
Name: father_profession, dtype: object

In [231]:
df["father_profession"] =df["father_profession"].fillna("IT")

In [233]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df["father_profession"] = oe.fit_transform(df[["father_profession"]])

In [235]:
df["fav_cuisine"].unique()

array(['Arabic cuisine', 'Italian', 'italian', 'Turkish ', 'Italian ',
       'African', 'Thai', 'Anything american style.', 'Seafood',
       'Orange chicken and chow mani noodles ', 'Chinese ',
       'italian food', 'Jamaican ', 'American or Italian ', 'Chicken ',
       'Mexican', 'Indian', 'italian ', 'Asian ', 'Chinese',
       "don't have one", 'Italian food ', 'Mexican ', 'Italian/German',
       'Indian food - samosas are amazing', 'mexican', 'Spanish',
       'French', 'American or Italian', 'Italian or Chinese ', 'chinese',
       'Thai food', 'Greek', 'American', 'All ', 'Sub sandwhiches',
       'Wraps ', "Chinese cuisine (General Tso's)", 'American ', 'Lean',
       nan, 'american ', 'Japanese', 'Any type of Colombian cuisine',
       'Mexican cuisine', 'Asian', 'Chinese food', 'mac and cheese',
       'Authentic Chinese and Vietnamese food ', 'italian and chinese',
       'Barbecue ', 'lebanese or greek', 'sushi', 'Indian food', 'Nepali',
       'I really love italian fo

In [236]:
df["fav_cuisine"].nunique()

60

In [237]:
df["fav_cuisine"].isna().sum()

2

In [238]:
df["fav_cuisine"] = df["fav_cuisine"].fillna(method='ffill')

In [240]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["fav_cuisine"] = le.fit_transform(df[["fav_cuisine"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [242]:
df["fav_food"].unique()

array([ 1.,  3.,  2., nan])

In [243]:
df["fav_food"].nunique()

3

In [246]:
df["fav_food"] = df["fav_food"].fillna(df["fav_food"].median())

In [248]:
df["food_childhood"].unique()

array(['rice  and chicken ',
       'chicken and biscuits, beef soup, baked beans',
       'mac and cheese, pizza, tacos', 'Beef stroganoff, tacos, pizza',
       'Pasta, chicken tender, pizza ', 'Fries, plaintain & fried fish',
       'grilled chicken, hamburgers',
       'chicken, cheesey potatoes, and hot dogs', 'Shrimp, spaghetti',
       'Pasta, Eggs, Pancakes ', 'Chicken', 'Scalloped potatoes and ham ',
       'Pizza, chicken wings, and corn on the cob ',
       'steak, lasagna, crab', 'Pizza', 'pizza',
       'Curry, Stew Chicken and Saltfish',
       'chicken fingers, steak, mac and cheese', 'manacotti',
       'pizza, chicken fingers', 'Pasta', 'pasta', 'Chicken Nuggets',
       'Spaghetti ', 'Chicken parm, beef stroganof, tacos',
       'Chicken Parm, Pizza ', 'Steak',
       'Deer Steak, Buttered Pasta, Garlic Pasta',
       'Crab legs, Mushroom soup, homemade rolls',
       'french fries, waffles, chocolate', 'chicken and biscuits',
       'Spaghetti, Chicken, Won Tons',
  

In [251]:
df["food_childhood"].nunique()

114

In [252]:
df["food_childhood"] = df["food_childhood"].fillna(method='ffill')

In [254]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["food_childhood"] = le.fit_transform(df[["food_childhood"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [256]:
df["healthy_meal"].unique()

array(['looks not oily ',
       'Grains, Veggies, (more of grains and veggies), small protein and fruit with dairy ',
       'usually includes natural ingredients; nonprocessed food',
       'Fresh fruits& vegetables, organic meats ',
       'A lean protein such as grilled chicken, green vegetables and  brown rice or other whole grain ',
       'Requires veggies, fruits and a cooked meal. ',
       'Protein, vegetables, fruit, and some carbs',
       'A healthy meal has a piece of meat followed by a lot of fruit and veggies',
       'Colorful', 'Chicken and rice with a side of veggies. ',
       'Chicken, and veggies ',
       'lean protein, veggies, fruit, complex carbs',
       'A salad with a reasonable amount of dressing and a meat.',
       'Lots of vegetabls with some grains like rice. Also has lean meat such as fish or chicken.',
       'Green and not greasy', 'chicken, veggies, rice',
       'Not too much carbs, a lot of protein, healthy fats and fruits and vegs ',
       'for

In [267]:
df["healthy_meal"] = df1["healthy_meal"]

In [262]:
df["healthy_meal"].isna().sum()

1

In [272]:
df["healthy_meal"] =df["healthy_meal"].fillna(method='bfill')

In [274]:
df['healthy_meal'].isna().sum()

0

In [276]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df["healthy_meal"] = oe.fit_transform(df[["healthy_meal"]])

In [278]:
df["ideal_diet"].unique()

array(['being healthy ',
       'Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.  ',
       'i would say my ideal diet is my current diet',
       'Healthy, fresh veggies/fruits & organic foods ',
       'Ideally I would like to be able to eat healthier foods in order to loose weight. ',
       'My ideal diet is to eat 3 times a day including breakfast on time. Eat healthy food. ',
       'I would ideally like to eat more fresh fruits and vegetables. However, its difficult to get to the store all the time to buy fresh.',
       'My ideal diet is filled with a lot of fruit and chicken. I also really enjoy eggs any type of way with toast.',
       'The same as it is now.',
       'Lots of protein, carbs, and fruits and veggies. ',
       'Chicken, fish ', 'More healthy varienty. ',
       'My ideal diet would be the proper portions of all food categories. I would also like to eat proteins around my workouts and avoid all d

In [279]:
df["ideal_diet"].nunique()

124

In [281]:
df["ideal_diet"].mode()

0                   3 healthy meals a day. No caffiene. 
1                                  3 smaller meals a day
2      A balance between meats and vegetables with le...
3      A balanced diet with each food group. Getting ...
4          A good breakfast. A healthy lunch and dinner.
                             ...                        
119    it would be a vegetarian diet without any red ...
120                                      lots of veggies
121    more healthy food such as vegetables than bad ...
122    my ideal diet would be more fruits and vegetab...
123    organic/healthy. fruits and vegetables but sti...
Name: ideal_diet, Length: 124, dtype: object

In [283]:
df["ideal_diet"] = df["ideal_diet"].fillna(method = 'bfill')

In [289]:
df["ideal_diet"].unique()

array(['being healthy ',
       'Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.  ',
       'i would say my ideal diet is my current diet',
       'Healthy, fresh veggies/fruits & organic foods ',
       'Ideally I would like to be able to eat healthier foods in order to loose weight. ',
       'My ideal diet is to eat 3 times a day including breakfast on time. Eat healthy food. ',
       'I would ideally like to eat more fresh fruits and vegetables. However, its difficult to get to the store all the time to buy fresh.',
       'My ideal diet is filled with a lot of fruit and chicken. I also really enjoy eggs any type of way with toast.',
       'The same as it is now.',
       'Lots of protein, carbs, and fruits and veggies. ',
       'Chicken, fish ', 'More healthy varienty. ',
       'My ideal diet would be the proper portions of all food categories. I would also like to eat proteins around my workouts and avoid all d

In [290]:
df["ideal_diet"].nunique()

124

In [291]:
df["ideal_diet"].isna().sum()

0

In [295]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["ideal_diet"] = le.fit_transform(df[["ideal_diet"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [302]:
df['income'].unique()

array([5.        , 4.        , 6.        , 1.        , 3.        ,
       2.        , 4.53225806])

In [301]:
mmm('income')

0    6.0
Name: income, dtype: float64
5.0
4.532258064516129


In [300]:
df["income"] = df["income"].fillna(df["income"].mean())

In [304]:
df["life_rewarding"] = df["life_rewarding"].fillna(method='bfill')

In [308]:
df["marital_status"].unique()

array([ 1.,  2.,  4., nan])

In [310]:
df["marital_status"] = df["marital_status"].fillna(method='ffill')

In [311]:
df["marital_status"].nunique()

3

In [315]:
df["mother_education"] = df["mother_education"].fillna(method='ffill')

In [313]:
df["meals_dinner_friend"] = df["meals_dinner_friend"].fillna(method='ffill')

In [318]:
df["mother_profession"] = df["mother_profession"].fillna(method='ffill')

In [319]:
df["on_off_campus"] = df["on_off_campus"].fillna(method='ffill')

In [323]:
df["self_perception_weight"] = df["self_perception_weight"].fillna(method='ffill')

In [324]:
df["soup"] = df["soup"].fillna(method='ffill')

In [325]:
df["sports"] = df["sports"].fillna(method='ffill')

In [321]:
df["persian_food"] = df["persian_food"].fillna(method='ffill')

In [330]:
df["tortilla_calories"] = df["tortilla_calories"].fillna(method='ffill')

In [329]:
df["type_sports"] = df["type_sports"].fillna(method='ffill')

In [328]:
df["weight"] = df["weight"].fillna(method='ffill')

In [ ]:
                1
turkey_calories                  0
type_sports                     21
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight

In [331]:
df.isna().sum()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  0
coffee                          0
comfort_food                    0
comfort_food_reasons            0
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    0
diet_current_coded              0
drink                           0
eating_changes                  0
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     0
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries         

In [333]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["weight"] = le.fit_transform(df[["weight"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [335]:
le = LabelEncoder()
df["type_sports"] = le.fit_transform(df[["type_sports"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [339]:

le = LabelEncoder()
df["mother_profession"] = le.fit_transform(df[["mother_profession"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [341]:
le = LabelEncoder()
df["meals_dinner_friend"] = le.fit_transform(df[["meals_dinner_friend"]])

C:\python 3.10\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [342]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           125 non-null    float64
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  125 non-null    float64
 5   calories_scone                125 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  125 non-null    int32  
 8   comfort_food_reasons          125 non-null    int32  
 9   comfort_food_reasons_coded    125 non-null    float64
 10  cook                          125 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       125 non-null    float64
 13  diet_

In [343]:
from sklearn.preprocessing import scale

In [344]:
df_clone = df.copy()

In [345]:
x = df_clone.values
x_std = scale(x)
x_std

array([[-2.66580169,  1.2453997 , -0.3551424 , ..., -1.02429504,
         0.9754899 ,  0.98195986],
       [ 0.61590039, -0.80295507, -0.3551424 , ...,  0.97628121,
        -0.70012396, -0.12885446],
       [-0.31051311, -0.80295507, -0.3551424 , ..., -1.02429504,
        -0.70012396,  2.00020633],
       ...,
       [ 1.2125735 , -0.80295507, -0.3551424 , ...,  0.97628121,
         0.9754899 , -1.42480451],
       [-1.0956093 ,  1.2453997 , -0.3551424 , ..., -1.02429504,
         0.9754899 , -0.77682948],
       [ 1.25967927, -0.80295507, -0.3551424 , ...,  0.97628121,
        -2.01235169, -0.77682948]])

In [348]:
scale = pd.DataFrame(x_std,columns=df.columns)

In [349]:
scale

GPA    Gender  breakfast  calories_chicken  calories_day  \
0   -2.665802e+00  1.245400  -0.355142         -1.127263      0.549441   
1    6.159004e-01 -0.802955  -0.355142          0.250061     -0.145462   
2   -3.105131e-01 -0.802955  -0.355142          1.091758      1.514392   
3   -5.722118e-01 -0.802955  -0.355142         -1.127263     -0.145462   
4    2.128843e-01 -0.802955  -0.355142          1.091758     -1.805316   
5   -3.058350e+00 -0.802955  -0.355142          0.250061     -0.145462   
6    9.979805e-01  1.245400  -0.355142          0.250061     -0.145462   
7   -3.105131e-01 -0.802955  -0.355142          1.091758     -0.145462   
8   -3.105131e-01 -0.802955  -0.355142         -1.127263      0.549441   
9   -3.105131e-01 -0.802955  -0.355142         -1.127263     -0.145462   
10   2.128843e-01 -0.802955  -0.355142          0.250061     -0.145462   
11   1.270147e+00 -0.802955  -0.355142          1.091758      1.514392   
12  -4.881438e-02  1.245400  -0.355142         -1.127263     -0.145462   
13   4.745831e-01 -0.802955  -0.355142          0.250061     -0.145462   
14  -8.339106e-01  1.245400  -0.355142          0.250061     -0.145462   
15  -1.162176e-15  1.245400   2.815772         -1.127263      0.549441   
16   1.521378e+00 -0.802955  -0.355142         -2.389809     -0.145462   
17   4.745831e-01  1.245400  -0.355142         -1.127263     -0.145462   
18  -4.881438e-02 -0.802955  -0.355142          1.091758     -0.145462   
19  -3.189199e+00  1.245400  -0.355142         -1.127263     -1.805316   
20  -3.105131e-01  1.245400  -0.355142          0.250061     -0.145462   
21   1.181170e+00  1.245400  -0.355142          0.250061     -0.145462   
22   7.362818e-01  1.245400  -0.355142          0.250061     -0.145462   
23   7.362818e-01  1.245400   2.815772          0.250061     -0.145462   
24   1.259679e+00 -0.802955  -0.355142          1.091758     -1.805316   
25  -1.619007e+00 -0.802955   2.815772          1.091758     -0.145462   
26   7.362818e-01  1.245400  -0.355142          0.250061     -1.805316   
27  -1.095609e+00  1.245400  -0.355142          0.250061      1.514392   
28  -5.722118e-01  1.245400  -0.355142          0.250061     -1.805316   
29   2.128843e-01  1.245400  -0.355142         -2.389809     -1.805316   
30   1.521378e+00 -0.802955  -0.355142          1.091758     -0.145462   
31   1.521378e+00  1.245400  -0.355142          0.250061     -0.145462   
32  -4.881438e-02  1.245400  -0.355142          0.250061     -0.145462   
33  -1.619007e+00 -0.802955  -0.355142          1.091758     -0.145462   
34   6.054324e-01 -0.802955  -0.355142          0.250061     -0.145462   
35  -1.095609e+00 -0.802955  -0.355142          0.250061     -1.805316   
36   7.362818e-01 -0.802955  -0.355142          0.250061     -0.145462   
37  -4.881438e-02 -0.802955  -0.355142          1.091758      1.514392   
38   1.233509e+00 -0.802955  -0.355142          0.250061     -0.145462   
39  -1.095609e+00  1.245400  -0.355142          1.091758      0.549441   
40  -4.881438e-02  1.245400  -0.355142         -1.127263     -0.145462   
41  -1.357308e+00 -0.802955  -0.355142          1.091758      1.514392   
42   4.745831e-01 -0.802955  -0.355142          0.250061     -0.145462   
43   2.128843e-01 -0.802955  -0.355142         -1.127263     -1.805316   
44  -5.722118e-01 -0.802955  -0.355142          0.250061      1.514392   
45   4.876680e-01 -0.802955  -0.355142          0.250061     -0.145462   
46   9.979805e-01  1.245400  -0.355142         -1.127263     -1.805316   
47  -1.619007e+00  1.245400  -0.355142         -1.127263      0.549441   
48   2.128843e-01  1.245400   2.815772         -1.127263      0.549441   
49   1.076490e+00  1.245400  -0.355142         -1.127263     -0.145462   
50   4.745831e-01  1.245400  -0.355142          1.091758     -0.145462   
51  -3.105131e-01  1.245400  -0.355142          0.250061      1.514392   
52  -3.105131e-01  1.245400  -0.355142          0.250061      1.514392   
53  -3.314490e-01 